### ISSUE TITLE
orbax is not compatible with python version of 3.10.0

### ISSUE THREAD

**Issue by NANDKLFSAJDKJHAjkhdsakxz1312** [dunnolab/xland-minigrid#41]
following error will appear:
ValueError: loop argument must agree with lock

**Comment by Howuhh** [comment]
Hi @NANDKLFSAJDKJHAjkhdsakxz1312! Given that latest orbax should be compatible with that python version (see https://github.com/google/orbax/blob/6a34d19c1217c4a77d53b8f2e6a172c8c6c9aef7/export/pyproject.toml#L10), It seems to be an orbax issue, not xminigrid (plus it doesn't reproduce locally for me). I would suggest trying to start an issue describing the problem directly in orbax project.
